image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/provider-mock
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}
vpa:
  enabled: false
  updatePolicy:
    updateMode: "Auto"

controllers:
  controlplane:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
  network:
    concurrentSyncs: 5
  operatingsystemconfig:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
    deployCRDs: false
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []
ignoreResources: false

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

webhookConfig:
  serverPort: 443

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  healthCheckConfig:
    syncPeriod: 30s
  etcd:
    storage:
      className: gardener.local-storage # TODO: storage class for local cluster
      capacity: 10Gi
#   backup:
#     schedule: "0 */24 * * *"

gardener:
  seed:
    provider: mock # TODO: seed provider = local?
