#!/bin/bash -e
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PROJECT_ROOT=$(dirname $0)/..
DEV_DIR=$PROJECT_ROOT/dev
EXAMPLE_DIR=$PROJECT_ROOT/example

MINIKUBE_KUBECONFIG=$DEV_DIR/minikube.kubecfg

[ -d $DEV_DIR ] || mkdir $DEV_DIR

_check_minikube () {
  if ! which minikube >/dev/null 2>/dev/null ; then
    >&2 echo "Minikube is not installed. See https://minikube.sigs.k8s.io/docs/start/ on how to get started with minikube."
    exit 1
  fi
}

_check_and_save_garden_kubecfg () {
  if ! kubectl get apiservices.apiregistration.k8s.io v1beta1.core.gardener.cloud --request-timeout=5 >/dev/null 2>/dev/null ; then
    >&2 echo "Please point your KUBECONFIG to your local Garden cluster"
    exit 1
  fi

  GARDEN_KUBECONFIG=$DEV_DIR/garden.kubecfg
  cat $KUBECONFIG > $GARDEN_KUBECONFIG
}
