#!/bin/bash -e
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname $0)/common

echo "> generating certificates for local development setup"

if ! which cfssl >/dev/null 2>/dev/null ; then
  >&2 echo "cfssl is not installed. Please refer to https://github.com/cloudflare/cfssl on how to install cfssl."
  exit 1
fi

cd $PROJECT_ROOT/tls/cfssl

echo "> generating CA cert"
cfssl gencert -initca ca-csr.json | cfssljson -bare ca -

echo "> generating server cert"
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=www server.json | cfssljson -bare server

echo "> copying certs to $PROJECT_ROOT/tls"
cp server.pem ../tls.crt
cp server-key.pem ../tls.key
