#!/bin/bash -e
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname $0)/common

echo "> checking minikube installation"
_check_minikube

_check_and_save_garden_kubecfg

export KUBECONFIG=$MINIKUBE_KUBECONFIG

echo "> unregistering minikube Seed"
kubectl --kubeconfig $GARDEN_KUBECONFIG delete seed local-seed --wait=false

until ! kubectl --kubeconfig $GARDEN_KUBECONFIG get seed local-seed >/dev/null 2>/dev/null ; do
  echo "waiting for seed 'local-seed' to be deleted..."
  sleep 2
done

kubectl --kubeconfig $GARDEN_KUBECONFIG -n garden delete secret local-seed --wait=false

if [ `minikube status | grep host | awk '{print $2}'` = "Running" ] ; then
  echo "> stopping minikube"
  minikube stop
else
  echo "minikube already stopped"
fi

echo "> done, you can now delete your minikube VM with 'minikube delete' if you want"
