#!/bin/bash -e
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source $(dirname $0)/common

echo "> checking minikube installation"
_check_minikube

_check_and_save_garden_kubecfg

export KUBECONFIG=$MINIKUBE_KUBECONFIG

if [ `minikube status 2>/dev/null | grep host | awk '{print $2}'` = "Running" ] ; then
  echo "minikube already running"
else
  echo "> starting minikube with virtualbox driver"
  # TODO: use node overcommitment to use smaller VM size
  # see: https://github.com/kubernetes/kubernetes/pull/86357
  minikube start \
    --cpus 6 \
    --memory 18gb \
    --vm-driver virtualbox \
    --embed-certs \
    --kubernetes-version=1.16.7 \
    --host-only-cidr='192.168.99.1/24' \
    --extra-config='kubeadm.pod-network-cidr=172.17.0.0/16' \
    --alsologtostderr=true \
    --v=10 \
    --wait=true --wait-timeout=5m
fi

echo "> installing MetalLB in minikube cluster"
kubectl apply -f $EXAMPLE_DIR/11-metallb-minikube.yaml

echo "> registering minikube as Seed 'local-seed'"
cat <<EOF > $DEV_DIR/secret-seed.yaml
apiVersion: v1
kind: Secret
metadata:
  name: local-seed
  namespace: garden
type: Opaque
stringData:
  kubeconfig: |
$(cat $KUBECONFIG | sed  's/^/    /')
EOF

kubectl --kubeconfig $GARDEN_KUBECONFIG apply -f $DEV_DIR/secret-seed.yaml
kubectl --kubeconfig $GARDEN_KUBECONFIG apply -f $EXAMPLE_DIR/35-seed.yaml

echo "> done, now you are ready to use your local minikube seed"
