# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Typha is disabled.
  typha_service_name: "none"
  # Configure the backend to use.
  calico_backend: "{{ .Values.config.backend }}"

  # Configure the MTU to use
  veth_mtu: "{{ .Values.config.veth_mtu }}"

  # The CNI network configuration to install on each node.  The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
        {{- if .Values.config.ipam.subnet }}
          "ipam": {
            "type": "{{ .Values.config.ipam.type }}",
            "subnet": "{{ .Values.config.ipam.subnet }}"
          },
        {{- else }}
          "ipam": {
            "type": "{{ .Values.config.ipam.type }}",
          },
        {{- end }}
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
