apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-logging-config
  namespace: garden
  labels:
    extensions.gardener.cloud/configuration: logging
{{ include "labels" . | indent 4 }}
data:
  filter-kubernetes.conf: |
