nodeCount: 1

images:
  hyperkube: "image-repository:image-tag"
  dind: "image-repository:image-tag"

resources:
  kubelet:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 100m
      memory: 400Mi
  dind:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi

worker:
  pool: "mock-worker"

ports:
  vpn:
    port: 4314
    nodePort: 30123

auth:
  bootstrapToken: abcdef.0123456789abcdef
  caCert: ""
